### ISSUE TITLE
Small parameter bug

### ISSUE THREAD

**Issue by Desseres** [translationexchange/tr8n_php_clientsdk#1]
Hey, I found a little problem. If not I will host it receives an error.
Init:
`<?php tr8n_init_client_sdk("YOUR_APPLICATION_KEY", "YOUR_APPLICATION_SECRET"); ?>`
Error:
`Fatal error: Call to a member function source() on a non-object in /vendor/tr8n/tr8n-client-sdk/library/Tr8n/Language.php on line 260`

When I give the host, everything works fine.
`<?php tr8n_init_client_sdk("YOUR_APPLICATION_KEY", "YOUR_APPLICATION_SECRET", "https://tr8nhub.com"); ?>`

Additionally id QuickStart Quide for PHP `http://translationexchange.com/tr8n/app/register/get_started` i find small bug. Step 2:
`<?php tr8n_init_client_sdk("https://tr8nhub.com", "YOUR_APPLICATION_KEY", "YOUR_APPLICATION_SECRET"); ?>`

It is wrong order for entering parameters.

I also have a question. Can I install a translation service on the local server? Nonstop synchronization with the server extremely slows loading the page.

**Comment by berk** [comment]
@Desseres we have completely redesigned the SDK initialization. It no longer needs key and secret, but only token. And we have moved the service from tr8nhub to translationexchange.com.
